/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: HASSAN (https://sketchfab.com/7ASSAN)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/wooden-door-8726b6c219a54ed585e096f267c2a35e
title: Wooden door
*/

import { useGLTF } from "@react-three/drei";
import Sprite from "./Sprite";

export default function Door(props) {
  const { nodes, materials } = useGLTF(
    process.env.PUBLIC_URL + "/assets/models/door/scene.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.None} />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Material.001"]}
        />
        <Sprite
          url={
            process.env.PUBLIC_URL +
            "/assets/models/door/textures/Door_sign.png"
          }
          scale={[1.4, 2.6, 1]}
          rotation={[Math.PI / 2, 0, 0]}
          position={[0, -0.1, 4.03]}
          useMeshBasicMaterial={true}
        ></Sprite>
      </group>
    </group>
  );
}
