/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 scene.gltf
Author: Loïc (https://sketchfab.com/loichuet1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gramophone-2458f980cf584c45a130df3fc39d47ff
Title: Gramophone
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Gramophone(props) {
  const { nodes, materials } = useGLTF("/assets/models/gramophone/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.DefaultMaterial}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}
