/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: RussianV0dka123 (https://sketchfab.com/russianv0dka123)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/detectives-office-in-noir-style-929e20ad5edf43c2963e778d95b03100
title: Detective's office in Noir style
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Office({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/assets/models/office/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.87, 2.59, -3.93]} scale={[2, 2.62, 1]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.bookshelf}
            />
          </group>
          <group position={[-2.46, 2.01, -4.44]} scale={[1.13, 1.17, 0.68]}>
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.drawers}
            />
          </group>
          <group position={[0.86, 1.76, -4.59]}>
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.paper}
            />
          </group>
          <group scale={5.2}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.wall_green}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.wall_wood}
            />
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group position={[5.03, 5.81, 0.91]} scale={[0.03, 0.11, 1]}>
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials.grey_metal}
            />
          </group>
          <group position={[1.93, 1.14, 1]}>
            <mesh
              castShadow
              geometry={nodes.Object_16.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group scale={2.03}>
            <mesh
              geometry={nodes.Object_18.geometry}
              material={materials.carpet}
            />
          </group>
          <group position={[0.86, 1.76, -4.59]}>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials.glass_glass}
            />
          </group>
          <group scale={5.2}>
            <mesh
              geometry={nodes.Object_23.geometry}
              material={materials.wood_floor}
            />
          </group>
          <group position={[0.86, 1.76, -4.59]}>
            <mesh
              geometry={nodes.Object_25.geometry}
              material={materials.green_metal}
            />
          </group>
          <group position={[2.38, 1.93, 0.06]} rotation={[0, -0.39, 0]}>
            <mesh
              geometry={nodes.Object_27.geometry}
              material={materials.cigar}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials.material}
            />
          </group>
          <group position={[0.86, 1.76, -4.59]}>
            <mesh
              geometry={nodes.Object_30.geometry}
              material={materials.grey_metal}
            />
          </group>
          <group position={[0.86, 1.76, -4.59]}>
            <mesh
              geometry={nodes.Object_32.geometry}
              material={materials.glass_glass}
            />
          </group>
          <group scale={5.2}>
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[2.05, 1.91, 0.49]}
            rotation={[Math.PI / 2, 0, -0.94]}
            scale={[0.01, 0.09, 0.01]}
          >
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials.dark_metal}
            />
            <mesh
              geometry={nodes.Object_37.geometry}
              material={materials.glass}
            />
          </group>
          <group position={[1.86, 1.92, 1.87]} scale={[0.07, 0.02, 0.07]}>
            <mesh
              geometry={nodes.Object_39.geometry}
              material={materials.liquor}
            />
          </group>
          <group position={[2.34, 2.01, -0.48]} scale={0.1}>
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials.liquor}
            />
          </group>
          <group
            position={[-3.09, 2.77, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_43.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[-1.71, 2.77, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_45.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[-1.71, 2.77, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[-3.09, 2.1, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_49.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[-1.71, 2.1, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[-3.09, 1.02, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[-1.71, 1.02, -3.68]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={1.12}
          >
            <mesh
              geometry={nodes.Object_55.geometry}
              material={materials.dark_wood}
            />
          </group>
          <group
            position={[3.29, 0.56, 1.21]}
            rotation={[0, 0.71, 0]}
            scale={0.05}
          >
            <mesh
              geometry={nodes.Object_57.geometry}
              material={materials.chair_wood}
            />
          </group>
          <group position={[1.87, 2.59, -3.93]} scale={[2, 2.62, 1]}>
            <mesh
              geometry={nodes.Object_59.geometry}
              material={materials.book}
            />
          </group>
          <group position={[4.09, 2.59, -3.93]} scale={[2, 2.62, 1]}>
            <mesh
              geometry={nodes.Object_61.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[3.37, 2.05, -3.34]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1.34, 1.76, 0.67]}
          >
            <mesh
              geometry={nodes.Object_63.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[2.68, 2.05, -3.34]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1.34, 1.76, 0.67]}
          >
            <mesh
              geometry={nodes.Object_65.geometry}
              material={materials.book}
            />
          </group>
          <group position={[1.86, 5.77, -3.93]} scale={[2, 2.62, 1]}>
            <mesh
              geometry={nodes.Object_67.geometry}
              material={materials.book}
            />
          </group>
          <group position={[-0.09, 3.03, -3.34]} scale={[1.63, 2.14, 0.82]}>
            <mesh
              geometry={nodes.Object_69.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[2.78, 4.15, -3.34]}
            rotation={[0, 0, -0.22]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_71.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[2.96, 4.15, -3.34]}
            rotation={[0, 0, -0.22]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_73.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[3.16, 4.15, -3.34]}
            rotation={[0, 0, -0.22]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_75.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[3.38, 4.15, -3.34]}
            rotation={[0, 0, -0.22]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_77.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[1.85, 0.99, -3.34]}
            rotation={[0, 0, -0.22]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_79.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[2.04, 0.99, -3.34]}
            rotation={[0, 0, -0.22]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_81.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[0.69, 3.06, -3.34]}
            rotation={[0, 0, 0.53]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_83.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[0.92, 3.07, -3.34]}
            rotation={[0, 0, 0.53]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_85.geometry}
              material={materials.book}
            />
          </group>
          <group
            position={[1.15, 3.07, -3.34]}
            rotation={[0, 0, 0.53]}
            scale={[1.91, 2.51, 0.96]}
          >
            <mesh
              geometry={nodes.Object_87.geometry}
              material={materials.book}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
